import { autogeneratedRules } from "$lib/coloring/3coloring-rules"
import { analyzeRules } from "$lib/coloring/rule-engine"
import type { WeightVector } from "$lib/coloring/rule-engine"
import {
	axisValue,
	buildCell,
	buildRuleColorMap,
	buildRuleIndexMap,
	extractGrowthBase,
	GRID_AXIS_COUNT,
	type WeightGridCell
} from "./weight-grid-shared"

export type GridWorkerInput = {
	type: "start"
	activeRuleNames: string[]
	axisCount?: number
}

export type GridWorkerCellMessage = {
	type: "cell"
	index: number
	cell: WeightGridCell
}

export type GridWorkerDoneMessage = {
	type: "done"
	bestWeights: WeightVector | null
	bestBase: number | null
}

export type GridWorkerErrorMessage = {
	type: "error"
	message: string
}

export type GridWorkerMessage =
	| GridWorkerCellMessage
	| GridWorkerDoneMessage
	| GridWorkerErrorMessage

const ruleGroups = autogeneratedRules
const ruleGroupNames = ruleGroups.map(group => group.map(rule => rule.name))
const allRules = ruleGroups.flat()
const ruleAnalyses = analyzeRules(allRules)
const ruleIndexMap = buildRuleIndexMap(allRules)
const ruleColorMap = buildRuleColorMap(allRules)

self.onmessage = async (event: MessageEvent<GridWorkerInput>) => {
	if (event.data?.type !== "start") return
	const { activeRuleNames, axisCount = GRID_AXIS_COUNT } = event.data

	try {
		let best: { weights?: WeightVector; base: number } = { base: Infinity }

		for (let i = 0; i < axisCount; i += 1) {
			const w3 = axisValue(i, axisCount)
			for (let j = 0; j < axisCount; j += 1) {
				const w2 = axisValue(j, axisCount)
				const index = i * axisCount + j

				const cell = await buildCell({
					w3,
					w2,
					activeRuleNames,
					ruleGroups: ruleGroupNames,
					ruleIndexMap,
					analyses: ruleAnalyses,
					ruleColorMap
				})
				const message: GridWorkerCellMessage = { type: "cell", index, cell }
				self.postMessage(message)
				const base = cell.solution ? extractGrowthBase(cell.solution) : null
				if (base !== null) {
					if (!best || base < best.base) {
						best = { weights: { w3: cell.w3, w2: cell.w2 }, base }
					}
				}
			}
		}
		const done: GridWorkerDoneMessage = {
			type: "done",
			bestWeights: best?.weights ?? null,
			bestBase: best?.base ?? null
		}
		self.postMessage(done)
	} catch (error) {
		const message: GridWorkerErrorMessage = {
			type: "error",
			message: error instanceof Error ? error.message : String(error)
		}
		self.postMessage(message)
	}
}
