import { Graph, type Color, type GraphNode } from "./graph-utils"
import type { BranchingRule } from "./rule-engine"

/**
 * Partials of nodes we'll use
 */
const v = { id: "v", role: "root" } as const
const v1 = { id: "v1", role: "root" } as const
const v2 = { id: "v2", role: "root" } as const
const a = { id: "a", role: "separator" } as const
const b = { id: "b", role: "separator" } as const
const c = { id: "c", role: "separator" } as const

/**
 * Enumerates every color list considered when generating canonical neighborhoods.
 */
const COLOR_LIST_OPTIONS = [
	[1, 2, 3],
	[1, 2],
	[1, 3],
	[2, 3]
] as const

/**
 * Exhaustively generates every canonical situation reachable under the eligible color lists.
 *
 * @returns Array of canonical situations representing the complete search space.
 */
export function* generateAllLocalSituations() {
	const edges = [
		{ from: "v", to: "a" },
		{ from: "v", to: "b" },
		{ from: "v", to: "c" }
	] as const
	const seen = new Set<string>()
	for (const rootColors of COLOR_LIST_OPTIONS)
		for (const aColors of COLOR_LIST_OPTIONS)
			for (const bColors of COLOR_LIST_OPTIONS)
				for (const cColors of COLOR_LIST_OPTIONS) {
					const nodes: GraphNode[] = [
						{ ...v, colors: rootColors },
						{ ...a, colors: aColors },
						{ ...b, colors: bColors },
						{ ...c, colors: cColors }
					]
					const canon = new Graph(nodes, edges).canon()
					if (!seen.has(canon.signature)) {
						yield canon
						seen.add(canon.signature)
					}
				}
}

/**
 * Memoized list of canonical situations produced at module load for reuse.
 */
export const ALL_LOCAL_SITUATIONS = Array.from(generateAllLocalSituations())

let autogeneratedRuleCounter = 0

/**
 * Generate all possible branching rules for a given local situation. Note that in general, canon
 * may have multiple roots, and we only want to enumerate assignments that are compatible.
 */
function autogenerateRules({
	canon,
	signature
}: {
	canon: Graph
	signature: string
}): BranchingRule[] {
	const roots = Array.from(canon.nodes).filter(node => node.role === "root")
	if (roots.length !== 1) return []

	const root = roots[0]
	if (root.colors.length === 0) return []

	const rules: BranchingRule[] = []

	const singletonBranches: BranchingRule["branches"] = root.colors.map(color => ({
		assignments: { [root.id]: [color] as readonly Color[] }
	}))

	rules.push({
		name: `Generated rule ${++autogeneratedRuleCounter}`,
		description: `Auto-generated for signature ${signature}`,
		before: canon,
		branches: singletonBranches
	})

	if (root.colors.length === 3) {
		const neighborIds = Array.from(canon.neighbors(root.id)).toSorted((a, b) => a.localeCompare(b))
		const seenTypes = new Set<string>()
		for (const color of root.colors) {
			const typeKey = neighborIds.filter(id => canon.nodeById(id)?.colors.includes(color)).join("|")
			if (seenTypes.has(typeKey)) continue
			seenTypes.add(typeKey)
			const remaining = root.colors.filter(c => c !== color) as readonly Color[]
			const splitBranches: BranchingRule["branches"] = [
				{ assignments: { [root.id]: [color] as readonly Color[] } },
				{ assignments: { [root.id]: remaining } }
			]
			rules.push({
				name: `Generated rule ${++autogeneratedRuleCounter}`,
				description: `Auto-generated split on ${root.id} for signature ${signature}`,
				before: canon,
				branches: splitBranches
			})
		}
	}

	return rules
}
export const autogeneratedRules: BranchingRule[][] = ALL_LOCAL_SITUATIONS.map(autogenerateRules)

/**
 * Curated catalog of branching rules used by the coloring rule engine demo cases.
 */
export const curatedRules: BranchingRule[] = [
	{
		name: "Degree ≥ 3, full list",
		description: "Vertex v has colors {1,2,3} and degree at least 3. Branch on the color of v.",
		before: new Graph(
			[
				{ ...v, colors: [1, 2, 3] },
				{ ...a, colors: [1, 2, 3] },
				{ ...b, colors: [1, 2, 3] },
				{ ...c, colors: [1, 2, 3] }
			],
			[
				{ from: "v", to: "a" },
				{ from: "v", to: "b" },
				{ from: "v", to: "c" }
			]
		),
		branches: [
			{ assignments: { v: [1] } },
			{ assignments: { v: [2] } },
			{ assignments: { v: [3] } }
		]
	},
	{
		name: "One‑vs‑two split",
		description: "Vertex v has colors {1,2,3}. Branch into v = 1 and v ∈ {2,3}.",
		before: new Graph(
			[
				{ ...v, colors: [1, 2, 3] },
				{ ...a, colors: [1, 2, 3] },
				{ ...b, colors: [1, 2, 3] },
				{ ...c, colors: [1, 2, 3] }
			],
			[
				{ from: "v", to: "a" },
				{ from: "v", to: "b" },
				{ from: "v", to: "c" }
			]
		),
		branches: [{ assignments: { v: [1] } }, { assignments: { v: [2, 3] } }]
	},
	{
		name: "Mixed neighbor lists for {1,2}-vertex",
		description:
			"Vertex v has colors {1,2}. Two neighbors have {1,3}, one neighbor has {2,3}. Branch on v = 1 vs v = 2.",
		before: new Graph(
			[
				{ ...v, colors: [1, 2] },
				{ ...a, colors: [1, 3] },
				{ ...b, colors: [1, 3] },
				{ ...c, colors: [2, 3] }
			],
			[
				{ from: "v", to: "a" },
				{ from: "v", to: "b" },
				{ from: "v", to: "c" }
			]
		),
		branches: [
			{
				assignments: { v: [1] }
			},
			{
				assignments: { v: [2] }
			}
		]
	},
	{
		name: "Same neighbor lists for {1,2}-vertex",
		description: "Vertex v has colors {1,2}. Three neighbors have {2,3}. Branch on v = 1 vs v = 2.",
		before: new Graph(
			[
				{ ...v, colors: [1, 2] },
				{ ...a, colors: [2, 3] },
				{ ...b, colors: [2, 3] },
				{ ...c, colors: [2, 3] }
			],
			[
				{ from: "v", to: "a" },
				{ from: "v", to: "b" },
				{ from: "v", to: "c" }
			]
		),
		branches: [
			{
				assignments: { v: [1] }
			},
			{
				assignments: { v: [2] }
			}
		]
	},
	{
		name: "Edge with two common neighbors",
		description:
			"Vertices v₁ and v₂ share neighbors u₁ and u₂. Branch on whether each vertex is fixed to 1 or remains in {2,3}.",
		before: new Graph(
			[
				{ ...v1, colors: [1, 2, 3] },
				{ ...v2, colors: [1, 2, 3] },
				{ ...a, colors: [1, 2, 3] },
				{ ...b, colors: [1, 2, 3] }
			],
			[
				{ from: "v1", to: "v2" },
				{ from: "v1", to: "a" },
				{ from: "v1", to: "b" },
				{ from: "v2", to: "a" },
				{ from: "v2", to: "b" }
			]
		),
		branches: [
			{
				assignments: { v1: [1], v2: [2, 3] }
			},
			{
				assignments: { v1: [2, 3], v2: [1] }
			},
			{
				assignments: { v1: [2, 3], v2: [2, 3] }
			}
		]
	},
	{
		name: "Generated rule 1",
		description: "Auto-generated for missing signature 12|123|13|23:111000",
		before: new Graph(
			[
				{ ...v, colors: [1, 2] },
				{ ...a, colors: [1, 2, 3] },
				{ ...b, colors: [1, 3] },
				{ ...c, colors: [2, 3] }
			],
			[
				{ from: "v", to: "a" },
				{ from: "v", to: "b" },
				{ from: "v", to: "c" }
			]
		),
		branches: [{ assignments: { v: [1] } }, { assignments: { v: [2] } }]
	},

	{
		name: "Generated rule 2",
		description: "Auto-generated for missing signature 13|123|12|23:111000",
		before: new Graph(
			[
				{ ...v, colors: [1, 3] },
				{ ...a, colors: [1, 2, 3] },
				{ ...b, colors: [1, 2] },
				{ ...c, colors: [2, 3] }
			],
			[
				{ from: "v", to: "a" },
				{ from: "v", to: "b" },
				{ from: "v", to: "c" }
			]
		),
		branches: [{ assignments: { v: [1] } }, { assignments: { v: [3] } }]
	},

	{
		name: "Generated rule 3",
		description: "Auto-generated for missing signature 23|123|12|13:111000",
		before: new Graph(
			[
				{ ...v, colors: [2, 3] },
				{ ...a, colors: [1, 2, 3] },
				{ ...b, colors: [1, 2] },
				{ ...c, colors: [1, 3] }
			],
			[
				{ from: "v", to: "a" },
				{ from: "v", to: "b" },
				{ from: "v", to: "c" }
			]
		),
		branches: [{ assignments: { v: [2] } }, { assignments: { v: [3] } }]
	},

	{
		name: "Generated rule 4",
		description: "Auto-generated for missing signature 123|12|13|23:111000",
		before: new Graph(
			[
				{ ...v, colors: [1, 2, 3] },
				{ ...a, colors: [1, 2] },
				{ ...b, colors: [1, 3] },
				{ ...c, colors: [2, 3] }
			],
			[
				{ from: "v", to: "a" },
				{ from: "v", to: "b" },
				{ from: "v", to: "c" }
			]
		),
		branches: [
			{ assignments: { v: [1] } },
			{ assignments: { v: [2] } },
			{ assignments: { v: [3] } }
		]
	},

	{
		name: "Generated rule 5",
		description: "Auto-generated for missing signature 123|123|12|13:111000",
		before: new Graph(
			[
				{ ...v, colors: [1, 2, 3] },
				{ ...a, colors: [1, 2, 3] },
				{ ...b, colors: [1, 2] },
				{ ...c, colors: [1, 3] }
			],
			[
				{ from: "v", to: "a" },
				{ from: "v", to: "b" },
				{ from: "v", to: "c" }
			]
		),
		branches: [
			{ assignments: { v: [1] } },
			{ assignments: { v: [2] } },
			{ assignments: { v: [3] } }
		]
	},
	{
		name: "Generated rule 6",
		description: "Auto-generated for missing signature 123|123|12|23:111000",
		before: new Graph(
			[
				{ ...v, colors: [1, 2, 3] },
				{ ...a, colors: [1, 2, 3] },
				{ ...b, colors: [1, 2] },
				{ ...c, colors: [2, 3] }
			],
			[
				{ from: "v", to: "a" },
				{ from: "v", to: "b" },
				{ from: "v", to: "c" }
			]
		),
		branches: [
			{ assignments: { v: [1] } },
			{ assignments: { v: [2] } },
			{ assignments: { v: [3] } }
		]
	},
	{
		name: "Generated rule 7",
		description: "Auto-generated for missing signature 123|123|13|23:111000",
		before: new Graph(
			[
				{ ...v, colors: [1, 2, 3] },
				{ ...a, colors: [1, 2, 3] },
				{ ...b, colors: [1, 3] },
				{ ...c, colors: [2, 3] }
			],
			[
				{ from: "v", to: "a" },
				{ from: "v", to: "b" },
				{ from: "v", to: "c" }
			]
		),
		branches: [
			{ assignments: { v: [1] } },
			{ assignments: { v: [2] } },
			{ assignments: { v: [3] } }
		]
	},
	{
		name: "Generated rule 8",
		description:
			"Auto-generated for missing signature separator.separator.separator.root#1,2,3|1,2,3|1,2|1,2,3#0001000100011110",
		before: new Graph(
			[
				{ id: "a", colors: [1, 2, 3], role: "separator" },
				{ id: "b", colors: [1, 2, 3], role: "separator" },
				{ id: "c", colors: [1, 2], role: "separator" },
				{ id: "v", colors: [1, 2, 3], role: "root" }
			],
			[
				{ from: "a", to: "v" },
				{ from: "b", to: "v" },
				{ from: "c", to: "v" }
			]
		),
		branches: [
			{ assignments: { v: [1] } },
			{ assignments: { v: [2] } },
			{ assignments: { v: [3] } }
		]
	},
	{
		name: "Generated rule 9",
		description:
			"Auto-generated for missing signature separator.separator.separator.root#1,2,3|1,2|1,2|1,2,3#0001000100011110",
		before: new Graph(
			[
				{ id: "a", colors: [1, 2, 3], role: "separator" },
				{ id: "b", colors: [1, 2], role: "separator" },
				{ id: "c", colors: [1, 2], role: "separator" },
				{ id: "v", colors: [1, 2, 3], role: "root" }
			],
			[
				{ from: "a", to: "v" },
				{ from: "b", to: "v" },
				{ from: "c", to: "v" }
			]
		),
		branches: [
			{ assignments: { v: [1] } },
			{ assignments: { v: [2] } },
			{ assignments: { v: [3] } }
		]
	},
	{
		name: "Generated rule 10",
		description:
			"Auto-generated for missing signature separator.separator.separator.root#1,2|1,2|1,2|1,2,3#0001000100011110",
		before: new Graph(
			[
				{ id: "a", colors: [1, 2], role: "separator" },
				{ id: "b", colors: [1, 2], role: "separator" },
				{ id: "c", colors: [1, 2], role: "separator" },
				{ id: "v", colors: [1, 2, 3], role: "root" }
			],
			[
				{ from: "a", to: "v" },
				{ from: "b", to: "v" },
				{ from: "c", to: "v" }
			]
		),
		branches: [
			{ assignments: { v: [1] } },
			{ assignments: { v: [2] } },
			{ assignments: { v: [3] } }
		]
	},
	{
		name: "Generated rule 11",
		description:
			"Auto-generated for missing signature separator.separator.separator.root#1,2|1,2|1,3|1,2,3#0001000100011110",
		before: new Graph(
			[
				{ id: "a", colors: [1, 2], role: "separator" },
				{ id: "b", colors: [1, 2], role: "separator" },
				{ id: "c", colors: [1, 3], role: "separator" },
				{ id: "v", colors: [1, 2, 3], role: "root" }
			],
			[
				{ from: "a", to: "v" },
				{ from: "b", to: "v" },
				{ from: "c", to: "v" }
			]
		),
		branches: [
			{ assignments: { v: [1] } },
			{ assignments: { v: [2] } },
			{ assignments: { v: [3] } }
		]
	},
	{
		name: "Generated rule 12",
		description:
			"Auto-generated for missing signature separator.separator.separator.root#1,2,3|1,2,3|1,2,3|1,2#0001000100011110",
		before: new Graph(
			[
				{ id: "a", colors: [1, 2, 3], role: "separator" },
				{ id: "b", colors: [1, 2, 3], role: "separator" },
				{ id: "c", colors: [1, 2, 3], role: "separator" },
				{ id: "v", colors: [1, 2], role: "root" }
			],
			[
				{ from: "a", to: "v" },
				{ from: "b", to: "v" },
				{ from: "c", to: "v" }
			]
		),
		branches: [{ assignments: { v: [1] } }, { assignments: { v: [2] } }]
	},
	{
		name: "Generated rule 13",
		description:
			"Auto-generated for missing signature separator.separator.separator.root#1,2,3|1,2,3|1,2|1,2#0001000100011110",
		before: new Graph(
			[
				{ id: "a", colors: [1, 2, 3], role: "separator" },
				{ id: "b", colors: [1, 2, 3], role: "separator" },
				{ id: "c", colors: [1, 2], role: "separator" },
				{ id: "v", colors: [1, 2], role: "root" }
			],
			[
				{ from: "a", to: "v" },
				{ from: "b", to: "v" },
				{ from: "c", to: "v" }
			]
		),
		branches: [{ assignments: { v: [1] } }, { assignments: { v: [2] } }]
	},
	{
		name: "Generated rule 14",
		description:
			"Auto-generated for missing signature separator.separator.separator.root#1,2,3|1,2,3|1,2|1,3#0001000100011110",
		before: new Graph(
			[
				{ id: "a", colors: [1, 3, 2], role: "separator" },
				{ id: "b", colors: [1, 3, 2], role: "separator" },
				{ id: "c", colors: [1, 2], role: "separator" },
				{ id: "v", colors: [1, 3], role: "root" }
			],
			[
				{ from: "a", to: "v" },
				{ from: "b", to: "v" },
				{ from: "c", to: "v" }
			]
		),
		branches: [{ assignments: { v: [1] } }, { assignments: { v: [3] } }]
	},
	{
		name: "Generated rule 15",
		description:
			"Auto-generated for missing signature separator.separator.separator.root#1,2,3|1,2|1,2|1,2#0001000100011110",
		before: new Graph(
			[
				{ id: "a", colors: [1, 2, 3], role: "separator" },
				{ id: "b", colors: [1, 2], role: "separator" },
				{ id: "c", colors: [1, 2], role: "separator" },
				{ id: "v", colors: [1, 2], role: "root" }
			],
			[
				{ from: "a", to: "v" },
				{ from: "b", to: "v" },
				{ from: "c", to: "v" }
			]
		),
		branches: [{ assignments: { v: [1] } }, { assignments: { v: [2] } }]
	},
	{
		name: "Generated rule 16",
		description:
			"Auto-generated for missing signature separator.separator.separator.root#1,2,3|1,2|1,3|1,2#0001000100011110",
		before: new Graph(
			[
				{ id: "a", colors: [1, 2, 3], role: "separator" },
				{ id: "b", colors: [1, 2], role: "separator" },
				{ id: "c", colors: [1, 3], role: "separator" },
				{ id: "v", colors: [1, 2], role: "root" }
			],
			[
				{ from: "a", to: "v" },
				{ from: "b", to: "v" },
				{ from: "c", to: "v" }
			]
		),
		branches: [{ assignments: { v: [1] } }, { assignments: { v: [2] } }]
	},
	{
		name: "Generated rule 17",
		description:
			"Auto-generated for missing signature separator.separator.separator.root#1,2,3|1,2|1,2|1,3#0001000100011110",
		before: new Graph(
			[
				{ id: "a", colors: [1, 3, 2], role: "separator" },
				{ id: "b", colors: [1, 2], role: "separator" },
				{ id: "c", colors: [1, 2], role: "separator" },
				{ id: "v", colors: [1, 3], role: "root" }
			],
			[
				{ from: "a", to: "v" },
				{ from: "b", to: "v" },
				{ from: "c", to: "v" }
			]
		),
		branches: [{ assignments: { v: [1] } }, { assignments: { v: [3] } }]
	},
	{
		name: "Generated rule 18",
		description:
			"Auto-generated for missing signature separator.separator.separator.root#1,2|1,2|1,2|1,2#0001000100011110",
		before: new Graph(
			[
				{ id: "a", colors: [1, 2], role: "separator" },
				{ id: "b", colors: [1, 2], role: "separator" },
				{ id: "c", colors: [1, 2], role: "separator" },
				{ id: "v", colors: [1, 2], role: "root" }
			],
			[
				{ from: "a", to: "v" },
				{ from: "b", to: "v" },
				{ from: "c", to: "v" }
			]
		),
		branches: [{ assignments: { v: [1] } }, { assignments: { v: [2] } }]
	},
	{
		name: "Generated rule 19",
		description:
			"Auto-generated for missing signature separator.separator.separator.root#1,2|1,2|1,3|1,2#0001000100011110",
		before: new Graph(
			[
				{ id: "a", colors: [1, 2], role: "separator" },
				{ id: "b", colors: [1, 2], role: "separator" },
				{ id: "c", colors: [1, 3], role: "separator" },
				{ id: "v", colors: [1, 2], role: "root" }
			],
			[
				{ from: "a", to: "v" },
				{ from: "b", to: "v" },
				{ from: "c", to: "v" }
			]
		),
		branches: [{ assignments: { v: [1] } }, { assignments: { v: [2] } }]
	},
	{
		name: "Generated rule 20",
		description:
			"Auto-generated for missing signature separator.separator.separator.root#1,2|1,2|1,3|1,3#0001000100011110",
		before: new Graph(
			[
				{ id: "a", colors: [1, 2], role: "separator" },
				{ id: "b", colors: [1, 2], role: "separator" },
				{ id: "c", colors: [1, 3], role: "separator" },
				{ id: "v", colors: [1, 3], role: "root" }
			],
			[
				{ from: "c", to: "v" },
				{ from: "a", to: "v" },
				{ from: "b", to: "v" }
			]
		),
		branches: [{ assignments: { v: [1] } }, { assignments: { v: [3] } }]
	},
	{
		name: "Generated rule 21",
		description:
			"Auto-generated for missing signature separator.separator.separator.root#1,2|1,3|2,3|1,2#0001000100011110",
		before: new Graph(
			[
				{ id: "a", colors: [1, 2], role: "separator" },
				{ id: "b", colors: [1, 3], role: "separator" },
				{ id: "c", colors: [2, 3], role: "separator" },
				{ id: "v", colors: [1, 2], role: "root" }
			],
			[
				{ from: "a", to: "v" },
				{ from: "b", to: "v" },
				{ from: "c", to: "v" }
			]
		),
		branches: [{ assignments: { v: [1] } }, { assignments: { v: [2] } }]
	}
] as const
